### ISSUE TITLE
Copyright enfrigement

### ISSUE THREAD

**Issue by fulmicoton** [chloneda/jutils#1]
This repo is containing copy pasted code from my repo without any license or credit.
https://github.com/fulmicoton/multiregexp/blob/master/LICENSE

**Comment by chloneda** [comment]
Hi, I made an update, is that OK?

**Comment by chloneda** [comment]
> This repo is containing copy pasted code from my repo without any license or credit.
> https://github.com/fulmicoton/multiregexp/blob/master/LICENSE

Hi, I made an update, is that OK?
